# SECURITY WARNING: This file contains speaker identity mappings
# NEVER expose this file to analysis LLMs or include in LLM-accessible manifests
# Only the orchestrator should read this file for organizational purposes

# Hash key stored in .env: ATTESOR_HASH_KEY
# This file maps real speaker identities to anonymized filenames

speaker_mappings:
  john_mccain:
    original_file: "original/john_mccain_2008_concession.txt"
    sanitized_hash: "a1c5e7d2"
    sanitized_file: "sanitized_english/sanitized_speech_a1c5e7d2.md"
    esperanto_hash: "c7cc43197100"
    esperanto_file: "sanitized_esperanto/c7cc43197100_esperanto.txt"
    
  mitt_romney:
    original_file: "original/mitt_romney_2020_impeachment.txt"
    sanitized_hash: "f9b8c2d7"
    sanitized_file: "sanitized_english/sanitized_speech_f9b8c2d7.md"
    esperanto_hash: "9c759f7025a4"
    esperanto_file: "sanitized_esperanto/9c759f7025a4_esperanto.txt"
    
  cory_booker:
    original_file: "original/cory_booker_2018_first_step_act.txt"
    sanitized_hash: "b3f7d2a6"
    sanitized_file: "sanitized_english/sanitized_speech_b3f7d2a6.md"
    esperanto_hash: "cccec508db40"
    esperanto_file: "sanitized_esperanto/cccec508db40_esperanto.txt"
    
  john_lewis:
    original_file: "original/john_lewis_1963_march_on_washington.txt"
    sanitized_hash: "c6d4a3e8"
    sanitized_file: "sanitized_english/sanitized_speech_c6d4a3e8.md"
    esperanto_hash: "6a2ff5ec9d0a"
    esperanto_file: "sanitized_esperanto/6a2ff5ec9d0a_esperanto.txt"
    
  jd_vance:
    original_file: "original/jd_vance_2022_natcon_conference.txt"
    sanitized_hash: "e2b9f5c1"
    sanitized_file: "sanitized_english/sanitized_speech_e2b9f5c1.md"
    esperanto_hash: "d07b5d29b51f"
    esperanto_file: "sanitized_esperanto/d07b5d29b51f_esperanto.txt"
    
  steve_king:
    original_file: "original/steve_king_2017_house_floor.txt"
    sanitized_hash: "d8a7b4f3"
    sanitized_file: "sanitized_english/sanitized_speech_d8a7b4f3.md"
    esperanto_hash: "ae288aeaa02a"
    esperanto_file: "sanitized_esperanto/ae288aeaa02a_esperanto.txt"
    
  bernie_sanders:
    original_file: "original/bernie_sanders_2025_fighting_oligarchy.txt"
    sanitized_hash: "a4c8e1d9"
    sanitized_file: "sanitized_english/sanitized_speech_a4c8e1d9.md"
    esperanto_hash: "052e6ebefc6c"
    esperanto_file: "sanitized_esperanto/052e6ebefc6c_esperanto.txt"
    
  alexandria_ocasio_cortez:
    original_file: "original/alexandria_ocasio_cortez_2025_fighting_oligarchy.txt"
    sanitized_hash: "7f9a2b8c"
    sanitized_file: "sanitized_english/sanitized_speech_7f9a2b8c.md"
    esperanto_hash: "8f7bb0ed3f89"
    esperanto_file: "sanitized_esperanto/8f7bb0ed3f89_esperanto.txt"

# ORCHESTRATOR INSTRUCTIONS:
# 1. Read this file only for organizational purposes
# 2. NEVER pass this file or its contents to analysis LLMs
# 3. Use hash mappings to organize results by speaker for analysis
# 4. Analysis LLMs should only see sanitized filenames without identity mappings 