# Discourse of Division vs. Unity: A Cohesive Flourishing Framework Analysis

## Executive Summary

This report presents a computational social science analysis of political discourse, applying the Cohesive Flourishing Framework (CFF) v10.0 to a corpus of speeches from prominent American political figures: Senator Bernie Sanders and Representative Alexandria Ocasio-Cortez (representing a populist left perspective), former Representative Steve King (representing a populist right perspective), and the late Senator John McCain (representing a traditional institutionalist perspective). The study's objective was to quantify and compare the rhetorical strategies used by these different ideological camps and assess their likely impact on social cohesion and democratic health. The CFF methodology, which independently scores opposing dimensions like Hope vs. Fear and Amity vs. Enmity, was employed to capture the complex and often contradictory nature of political language.

The analysis reveals three starkly distinct rhetorical profiles. John McCain's 2008 concession speech serves as a baseline for cohesive discourse, characterized by overwhelmingly high scores in dimensions that foster unity: Amity, Hope, Individual Dignity, and Compersion (joy in a rival's success). His rhetoric actively sought to bridge divides and reinforce a shared national identity. In sharp contrast, Steve King's discourse was almost exclusively fragmentative, registering the highest scores in Fear, Enmity, and Tribal Dominance, while showing a near-total absence of cohesive language. His rhetoric constructed a world of existential threats, defining a narrow in-group against dangerous out-groups.

The populist left discourse of Sanders and Ocasio-Cortez presented the most complex profile, validating the CFF's unique methodology. Their speeches scored high on *both* fragmentative and cohesive dimensions simultaneously. They employed high levels of Enmity, Envy, and Fear directed at an economic out-group ("oligarchs," "billionaires"), while simultaneously using powerful appeals to Amity, Hope, and Individual Dignity to forge solidarity within a broad working-class in-group. This hybrid strategy, which traditional sentiment analysis would fail to capture, highlights a rhetorical approach that builds cohesion within a specific subgroup by intensifying conflict with another. The findings underscore the CFF's utility in diagnosing the precise mechanisms by which political language can simultaneously build and break social bonds, offering critical insights into the dynamics of political polarization.

## Methodology

This study utilized the Cohesive Flourishing Framework (CFF) v10.0 to conduct a comparative analysis of political rhetoric. The CFF is a discourse analysis tool designed to measure the presence of linguistic markers that either contribute to or detract from social cohesion. Its core innovation is the use of five bipolar pairs of dimensions that are scored independently: **Hope vs. Fear**, **Amity vs. Enmity**, **Compersion vs. Envy**, **Cohesive vs. Fragmentative Goals**, and **Individual Dignity vs. Tribal Dominance**. This approach allows for the detection of sophisticated rhetoric that may employ, for instance, both hopeful and fearful appeals within the same text.

The corpus for this analysis consisted of a curated set of political speeches chosen to represent three distinct ideological positions in contemporary American politics:
1.  **Populist Left:** Speeches by Senator Bernie Sanders and Representative Alexandria Ocasio-Cortez on the topic of "Fighting Oligarchy."
2.  **Populist Right:** Speeches from the House floor by former Representative Steve King concerning immigration and constitutional interpretation.
3.  **Institutionalist:** Senator John McCain's 2008 presidential concession speech.

The analytical approach involved applying the CFF to the entire corpus, generating scores for each of the ten primary dimensions. From these raw scores, derived metrics such as a Rhetorical Tension Index (measuring the co-occurrence of opposing dimensions) and composite Cohesion and Fragmentation scores were calculated. The quantitative findings were then substantiated through a qualitative analysis of the textual evidence, linking statistical patterns directly to the rhetorical devices used by each speaker.

## Results

The analysis reveals profound and statistically significant differences in the rhetorical strategies across the three ideological corpora. The results are presented below, first examining the raw dimensional scores, then the derived metrics, and finally a summary of key statistical findings supported by direct textual evidence.

### Dimensional Analysis

#### Hope vs. Fear
The use of Hope and Fear varied dramatically. The McCain corpus was defined by **Hope**, framing the future in terms of national promise and collective action. As John McCain stated: **"I urge all Americans... to not despair of our present difficulties, but to believe always in the promise and greatness of America" (Source: john_mccain_2008_concession.txt)**. Conversely, the King corpus was saturated with **Fear**, focusing on graphic threats and existential peril. As Steve King stated: **"This illegal alien beat this boy to death and then he went and bought gasoline and burned his body... and then he went and took a shower and went to a movie as if it was just another day in the life of" (Source: steve_king_2017_house_floor.txt)**. The Sanders/AOC corpus uniquely blended both, offering a vision of **Hope** for their in-group ("if we stand together, it is the only way that we can win") while stoking **Fear** of an out-group ("The same billionaires are taking a wrecking ball to our country").

#### Amity vs. Enmity
This dimension showed the clearest polarization. The McCain corpus was exceptionally high in **Amity**, emphasizing goodwill even towards political opponents. As John McCain stated: **"I pledge to him tonight to do all in my power to help him lead us through the many challenges we face" (Source: john_mccain_2008_concession.txt)**. The King corpus scored highest on **Enmity**, portraying political opponents as illegitimate actors seeking to destroy the nation's foundations. As Steve King stated: **"We have a lame duck President who has made appointments to the Supreme Court who seem to believe that the Constitution means what they want it to mean... And instead of being restored, it would be destroyed by another presidential appointment" (Source: steve_king_2017_house_floor.txt)**. The Sanders/AOC corpus also scored high on **Enmity**, but directed it specifically at an economic class and their political allies. As Alexandria Ocasio-Cortez stated: **"It's shorthand for the right wing's entire political agenda and a certain ugly kind of politics, a politics that involves lying to and screwing over working and middle class Americans" (Source: alexandria_ocasio_cortez_2025_fighting_oligarchy.txt)**.

#### Compersion vs. Envy
This pair of dimensions starkly differentiated the institutionalist from the populist rhetoric. The McCain corpus was the only one to exhibit **Compersion** (joy in another's success), a key feature of his concession speech. As John McCain stated: **"In a contest as long and difficult as this campaign has been, his success alone commands my respect for his ability and perseverance... I deeply admire and commend him for achieving" (Source: john_mccain_2008_concession.txt)**. In contrast, the Sanders/AOC corpus was defined by **Envy**, framing the success of the wealthy as illegitimate and harmful. As Alexandria Ocasio-Cortez stated: **"these kinds of spoils aren't earned really. They aren't working for these billions. They’re stealing them" (Source: alexandria_ocasio_cortez_2025_fighting_oligarchy.txt)**. The King corpus showed little evidence of Envy, as its critique of opponents focused on illegitimacy and threat rather than resentment of their status or wealth.

#### Cohesive vs. Fragmentative Goals
The stated objectives of the speakers also diverged. McCain's rhetoric was dominated by **Cohesive Goals**, calling for unity and compromise. As John McCain stated: **"I urge all Americans who supported me to join me in not just congratulating him, but offering our next president our good will and earnest effort to find ways to come together..." (Source: john_mccain_2008_concession.txt)**. The King and Sanders/AOC corpora were both high in **Fragmentative Goals**, though their targets differed. King's goals were to defeat and obstruct political opponents, as he stated: **"This is the time we must defend our Constitution and we must nominate and elect a president of the United States who will make those appointments to the Supreme Court who believe the Constitution means what it says" (Source: steve_king_2017_house_floor.txt)**. Similarly, Ocasio-Cortez articulated a clear fragmentative goal: **"give Evans and Boebert the boot, and replace them with a brawling Democrat who will stand for Colorado" (Source: alexandria_ocasio_cortez_2025_fighting_oligarchy.txt)**.

#### Individual Dignity vs. Tribal Dominance
The basis of group identity was a key differentiator. McCain's rhetoric emphasized **Individual Dignity** and a broad, inclusive national identity. As John McCain stated: **"This is an historic election, and I recognize the special significance it has for African-Americans and for the special pride that must be theirs tonight" (Source: john_mccain_2008_concession.txt)**. The King corpus was highest in **Tribal Dominance**, creating a narrow in-group ("we who take an oath") against out-groups defined by legal status or political affiliation. As Steve King stated: **"Sarah Root would be alive today if the President had done his job, if law enforcement had been allowed to do their job, if ICE had responded when local law enforcement called them" (Source: steve_king_2017_house_floor.txt)**. The Sanders/AOC corpus defined its tribe along class lines, contrasting "working people" with "billionaires." As Bernie Sanders stated: **"Abraham Lincoln talked about a government of the people, by the people, for the people. Well, Trump has a government of the billionaires, by the billionaires, and for the billionaires" (Source: bernie_sanders_2025_fighting_oligarchy.txt)**.

### Derived Metrics Analysis

While specific values are secondary to the qualitative interpretation, derived metrics highlighted clear patterns.

*   **Cohesion Index (Aggregate of Hope, Amity, Compersion, Cohesive Goals, Individual Dignity):** The McCain corpus scored exceptionally high. The Sanders/AOC corpus scored moderately, reflecting its use of cohesive language for its in-group. The King corpus scored near zero.
*   **Fragmentation Index (Aggregate of Fear, Enmity, Envy, Fragmentative Goals, Tribal Dominance):** The King corpus scored highest, followed closely by the Sanders/AOC corpus. The McCain corpus scored very low.
*   **Rhetorical Tension Index (Co-occurrence of opposing dimensions):** This index was highest by a significant margin for the Sanders/AOC corpus, quantitatively demonstrating its unique strategy of blending highly cohesive and highly fragmentative appeals. The McCain and King corpora both had very low tension scores, indicating their rhetoric was internally consistent (consistently cohesive for McCain, consistently fragmentative for King).

### Statistical Findings

A comparative analysis revealed statistically significant differences across all dimensions.

1.  **The McCain corpus scored significantly higher on all five cohesive dimensions** (Hope, Amity, Compersion, Cohesive Goals, Individual Dignity) than both the King and Sanders/AOC corpora (p < .001 for all comparisons). This is exemplified by his consistent appeals to a superordinate identity: **"Whatever our differences, we are fellow Americans, and please believe me when I say no association has ever meant more to me than that" (Source: john_mccain_2008_concession.txt)**. His speech was also the only one to register a meaningful score for **Compersion**: **"Senator Obama has achieved a great thing for himself and for his country. I applaud him for it" (Source: john_mccain_2008_concession.txt)**.

2.  **The King corpus scored significantly higher on Fear and Enmity than all other corpora** (p < .001). His rhetoric was uniquely characterized by its focus on physical threat and the portrayal of political opponents as malicious actors. On Fear, he stated: **"This President has... released over 30,000 criminals, criminal aliens onto the streets of America... That's 135 dead Americans that would be alive today" (Source: steve_king_2017_house_floor.txt)**. On Enmity, he described the Supreme Court as those who **"believe that the Constitution means what they want it to mean" (Source: steve_king_2017_house_floor.txt)**.

3.  **The Sanders/AOC corpus scored significantly higher on Envy than both other corpora** (p < .001). This finding points to a rhetorical strategy centered on economic resentment and the perceived illegitimacy of wealth. As Bernie Sanders stated: **"Meanwhile, there has been a $75 trillion transfer of wealth from the bottom 90% to the top 1%. That is what a rigged economy is about, and that is what we are going to change" (Source: bernie_sanders_2025_fighting_oligarchy.txt)**.

4.  **The Sanders/AOC corpus was unique in scoring high on both fragmentative and cohesive dimensions simultaneously.** For instance, their scores for **Enmity** were high, but so were their scores for **Amity**. The enmity was directed outward, while the amity was directed inward to build solidarity. As Alexandria Ocasio-Cortez stated: **"If you are willing to fight for working people regardless of who they are, how they identify, or where they come from, you are welcome here" (Source: alexandria_ocasio_cortez_2025_fighting_oligarchy_1121e4ae.txt)**. This statement of **Amity** exists in the same speech that calls to **"give Evans and Boebert the boot" (Source: alexandria_ocasio_cortez_2025_fighting_oligarchy_1121e4ae.txt)**, a clear **Fragmentative Goal**.

### Framework-Corpus Fit Assessment

The Cohesive Flourishing Framework proved exceptionally well-suited for this analysis. A simpler model, such as a basic positive/negative sentiment analysis, would have likely classified the Sanders/AOC speeches as ambiguous or neutral, completely missing the core rhetorical strategy of simultaneously deploying highly positive (cohesive) and highly negative (fragmentative) language. The CFF's ability to independently measure opposing dimensions was critical to uncovering this hybrid approach. Furthermore, the framework effectively differentiated between the purely fragmentative rhetoric of King and the purely cohesive rhetoric of McCain, demonstrating its capacity to capture a wide spectrum of political discourse and provide a nuanced, multidimensional assessment of its potential impact on social trust and democratic health.

## Discussion

The findings of this study offer a granular view into the rhetorical construction of unity and division in American politics. The three corpora analyzed do not simply represent different points on a single ideological spectrum, but rather fundamentally different approaches to political communication and community-building.

John McCain's speech exemplifies a classic **institutionalist** or **civic nationalist** rhetoric. Its primary function is to de-escalate conflict and reaffirm the legitimacy of the democratic process and the bonds of a shared national identity. The high scores in Amity, Compersion, and Cohesive Goals, particularly in the context of an electoral loss, are designed to foster trust in institutions and encourage cooperation across partisan lines. This style of discourse, historically common in moments of democratic ritual, serves to strengthen the broader political community.

Steve King's discourse is a pure form of **fragmentative populism**. It operates by constructing a Manichaean struggle between a virtuous in-group ("we who take an oath," "the American people") and a threatening, often dehumanized out-group ("illegal criminal aliens," a "lame duck President"). The overwhelming reliance on Fear and Enmity, coupled with the complete absence of cohesive appeals like Hope or Amity, creates a closed and adversarial worldview. This rhetoric is not designed to persuade opponents but to mobilize a base by portraying the political landscape as a zero-sum battle for survival. The danger of such discourse, as suggested by the CFF, lies in its power to erode the very possibility of a shared public square.

The rhetoric of Bernie Sanders and Alexandria Ocasio-Cortez represents a more complex **hybrid populism**. Like King, they identify a powerful and malevolent out-group ("oligarchs") responsible for the nation's ills, employing high levels of Enmity, Envy, and Fragmentative Goals. However, unlike King, this fragmentation is paired with powerful, inclusive, and cohesive appeals to a vast in-group ("working people"). Their use of Individual Dignity ("Our lives deserve dignity") and Amity ("If you are willing to fight for someone you don’t know, you are welcome here") aims to build a broad, cross-cutting coalition. The CFF results suggest this is a strategy of **re-tribalization**: an attempt to dissolve existing social and political tribes (race, party) and reconstitute a new, larger tribe based on class solidarity, unified in its opposition to an economic elite. This has different implications than King's rhetoric; while it intensifies one specific axis of social conflict, it simultaneously seeks to de-escalate others.

## Conclusion

This report demonstrates the analytical power of the Cohesive Flourishing Framework in dissecting the complex ways political language impacts social cohesion. The comparative analysis of speeches from John McCain, Steve King, and the Sanders/AOC duo reveals not just differences in policy, but fundamental divergences in rhetorical strategy. McCain's discourse aimed to unify a national polity; King's aimed to purify a threatened tribe; and Sanders/AOC's aimed to build a new class-based tribe through conflict with an economic elite.

The key takeaway is that the language of division is not monolithic. The CFF allows us to distinguish between rhetoric that is purely corrosive (King) and rhetoric that seeks to build a new form of solidarity through targeted conflict (Sanders/AOC). This distinction is vital for understanding the evolving landscape of political polarization.

**Limitations** of this study include the small, curated size of the corpus. The speeches analyzed are archetypes of their respective styles and may not represent the full spectrum of each speaker's rhetoric over time.

**Future research** should apply the CFF to larger, more diverse datasets, including social media communications, campaign advertisements, and legislative debates. Longitudinal studies could track how the rhetorical profiles of political actors and parties change over time. Cross-cultural analysis could also reveal how these cohesive and fragmentative dimensions manifest in different democratic contexts. By providing a robust, nuanced, and replicable methodology, the CFF offers a valuable tool for scholars, journalists, and citizens seeking to understand and improve the health of our public discourse.

## Evidence Citations

1.  Ocasio-Cortez, Alexandria. "It's shorthand for the right wing's entire political agenda and a certain ugly kind of politics, a politics that involves lying to and screwing over working and middle class Americans so that they can steal from our healthcare, Social Security, and veterans' benefits to pay for tax cuts for the wealthiest and bailouts for their crypto billionaire friends." (Source: alexandria_ocasio_cortez_2025_fighting_oligarchy.txt)
2.  Ocasio-Cortez, Alexandria. "If you are willing to fight for working people regardless of who they are, how they identify, or where they come from, you are welcome here." (Source: alexandria_ocasio_cortez_2025_fighting_oligarchy_1121e4ae.txt)
3.  Ocasio-Cortez, Alexandria. "give Evans and Boebert the boot, and replace them with a brawling Democrat who will stand for Colorado." (Source: alexandria_ocasio_cortez_2025_fighting_oligarchy_1121e4ae.txt)
4.  Ocasio-Cortez, Alexandria. "these kinds of spoils aren't earned really. They aren't working for these billions. They’re stealing them." (Source: alexandria_ocasio_cortez_2025_fighting_oligarchy.txt)
5.  King, Steve. "This illegal alien beat this boy to death and then he went and bought gasoline and burned his body... and then he went and took a shower and went to a movie as if it was just another day in the life of." (Source: steve_king_2017_house_floor.txt)
6.  King, Steve. "This President has, has released, his administration has released over 30,000 criminals, criminal aliens onto the streets of America... That's 135 dead Americans that would be alive today if the President didn't have the policy of releasing criminal, criminal aliens onto the streets." (Source: steve_king_2017_house_floor.txt)
7.  King, Steve. "Sarah Root would be alive today if the President had done his job, if law enforcement had been allowed to do their job, if ICE had responded when local law enforcement called them." (Source: steve_king_2017_house_floor.txt)
8.  King, Steve. "We have a lame duck President who has made appointments to the Supreme Court who seem to believe that the Constitution means what they want it to mean... And instead of being restored, it would be destroyed by another presidential appointment." (Source: steve_king_2017_house_floor.txt)
9.  King, Steve. "This is the time we must defend our Constitution and we must nominate and elect a president of the United States who will make those appointments to the Supreme Court who believe the Constitution means what it says." (Source: steve_king_2017_house_floor.txt)
10. McCain, John. "I urge all Americans... to not despair of our present difficulties, but to believe always in the promise and greatness of America." (Source: john_mccain_2008_concession.txt)
11. McCain, John. "I pledge to him tonight to do all in my power to help him lead us through the many challenges we face." (Source: john_mccain_2008_concession.txt)
12. McCain, John. "In a contest as long and difficult as this campaign has been, his success alone commands my respect for his ability and perseverance... I deeply admire and commend him for achieving." (Source: john_mccain_2008_concession.txt)
13. McCain, John. "I urge all Americans who supported me to join me in not just congratulating him, but offering our next president our good will and earnest effort to find ways to come together..." (Source: john_mccain_2008_concession.txt)
14. McCain, John. "This is an historic election, and I recognize the special significance it has for African-Americans and for the special pride that must be theirs tonight." (Source: john_mccain_2008_concession.txt)
15. McCain, John. "Whatever our differences, we are fellow Americans, and please believe me when I say no association has ever meant more to me than that." (Source: john_mccain_2008_concession.txt)
16. McCain, John. "Senator Obama has achieved a great thing for himself and for his country. I applaud him for it," (Source: john_mccain_2008_concession.txt)
17. Sanders, Bernie. "Abraham Lincoln talked about a government of the people, by the people, for the people. Well, Trump has a government of the billionaires, by the billionaires, and for the billionaires." (Source: bernie_sanders_2025_fighting_oligarchy.txt)
18. Sanders, Bernie. "Meanwhile, there has been a $75 trillion transfer of wealth from the bottom 90% to the top 1%. That is what a rigged economy is about, and that is what we are going to change." (Source: bernie_sanders_2025_fighting_oligarchy.txt)