# Emotional Climate Framework (ECF) v6.0

**Version**: 6.0
**Status**: Active
**Major Change**: JSON-First Architecture with Enhanced Synthesis Integration

---

## Overview

ECF analyzes emotional atmosphere in political discourse through six dimensions, independent of rhetorical strategy, speaker character, or institutional effects. Measures psychological environment that discourse generates.

**Purpose**: Objective measurement of emotional climate for audience response prediction and message optimization.

**NEW IN V6.0**: Returns to JSON-first output architecture while maintaining all analytical capabilities from v5.0, eliminating CSV parsing brittleness while preserving synthesis scalability.

---

## Dimensions

#### Fear (Crisis/Threat Climate) (0.0-1.0)
**Definition**: Language emphasizing danger, threat, vulnerability, crisis, or existential risk.
**Key Markers**: "emergency," "crisis," "under attack," "running out of time," "defenseless"

#### Hope (Opportunity/Progress Climate) (0.0-1.0)  
**Definition**: Language emphasizing positive possibilities, progress, improvement, or achievement potential.
**Key Markers**: "opportunity," "breakthrough," "bright future," "great potential," "optimistic"

#### Enmity (Hostility/Conflict Climate) (0.0-1.0)
**Definition**: Language creating antagonistic atmosphere toward opponents, enemies, or opposing groups.
**Key Markers**: "enemy," "betrayal," "fight against," "destroy," "combat"

#### Amity (Friendship/Unity Climate) (0.0-1.0)
**Definition**: Language fostering positive relationships, cooperation, solidarity, or shared purpose.
**Key Markers**: "together," "unity," "partnership," "cooperation," "shared values"

#### Envy (Resentment/Grievance Climate) (0.0-1.0)
**Definition**: Language expressing resentment toward others' advantages, success, or privileged positions.
**Key Markers**: "unfair advantage," "privileged elite," "deserve better," "left behind," "rigged system"

#### Compersion (Celebration/Merit Climate) (0.0-1.0)
**Definition**: Language celebrating others' success, merit, achievement, or positive developments.
**Key Markers**: "congratulations," "well-deserved," "earned success," "inspiring achievement," "celebration"

---

<details><summary>Machine-Readable Configuration</summary>

```json
{
  "name": "ecf_v6_0",
  "version": "v6.0",
  "display_name": "Emotional Climate Framework v6.0",
  "analysis_variants": {
    "default": {
      "description": "Complete emotional climate analysis with structured JSON output.",
      "analysis_prompt": "Phase 1: Cognitive Priming: You are an expert analyst of emotional climate and psychological atmosphere in political discourse. Phase 2: Framework Methodology: Your task is to analyze the emotional climate generated by the provided text using the Emotional Climate Framework v6.0. This framework measures the psychological environment through six key dimensions: Fear, Hope, Enmity, Amity, Envy, and Compersion. Phase 3: Operational Definitions: Evaluate each dimension: Fear (crisis/threat language), Hope (opportunity/progress language), Enmity (hostility/conflict language), Amity (unity/cooperation language), Envy (resentment/grievance language), Compersion (celebration/merit language). Phase 4: Scoring Protocol: For each dimension, provide ONLY: (1) Raw score (0.0-1.0) based on emotional strength, (2) Salience score (0.0-1.0) based on prominence in the message, (3) Confidence score (0.0-1.0) based on evidence strength, (4) Supporting quotes with contextual analysis. DO NOT perform any mathematical calculations or compute derived metrics like polarity or intensity. Phase 5: JSON Structure Requirements: Your response must be a structured JSON object with nested data for raw scores only (NO calculated metrics), evidence organized by dimension, and reasoning for each assessment. Phase 6: Output Specification: Return a single, valid JSON object with raw dimensional scores only - NO calculations or derived metrics. All mathematical processing will be handled by code execution."
    }
  },
  "dimension_groups": {
    "threat_opportunity": ["fear", "hope"],
    "social_relations": ["enmity", "amity"],
    "resource_attitudes": ["envy", "compersion"]
  },
  "calculation_spec": {
    "emotional_polarity": "(hope + amity + compersion) - (fear + enmity + envy)",
    "climate_intensity": "(fear + hope + enmity + amity + envy + compersion) / 6"
  },
  "reliability_rubric": {
    "cronbachs_alpha": {
      "excellent": [0.80, 1.0],
      "good": [0.70, 0.79],
      "acceptable": [0.60, 0.69],
      "poor": [0.0, 0.59]
    }
  },
  "output_contract": {
    "schema": {
      "worldview": "string",
      "scores": "object",
      "evidence": "object",
      "reasoning": "object",
      "salience_ranking": "array",
      "climate_analysis": "object"
    },
    "structured_data_requirements": {
      "scores": {
        "description": "Nested object containing all dimensional scores and calculated metrics",
        "structure": {
          "dimensions": {
            "fear": {
              "score": "number (0.0-1.0)",
              "salience": "number (0.0-1.0)",
              "confidence": "number (0.0-1.0)"
            },
            "hope": {
              "score": "number (0.0-1.0)",
              "salience": "number (0.0-1.0)",
              "confidence": "number (0.0-1.0)"
            },
            "enmity": {
              "score": "number (0.0-1.0)",
              "salience": "number (0.0-1.0)",
              "confidence": "number (0.0-1.0)"
            },
            "amity": {
              "score": "number (0.0-1.0)",
              "salience": "number (0.0-1.0)",
              "confidence": "number (0.0-1.0)"
            },
            "envy": {
              "score": "number (0.0-1.0)",
              "salience": "number (0.0-1.0)",
              "confidence": "number (0.0-1.0)"
            },
            "compersion": {
              "score": "number (0.0-1.0)",
              "salience": "number (0.0-1.0)",
              "confidence": "number (0.0-1.0)"
            }
          },

          "metadata": {
            "total_dimensions": "number",
            "analysis_completeness": "number (0.0-1.0)"
          }
        }
      },
      "evidence": {
        "description": "Nested object containing structured evidence data for audit and replication",
        "structure": {
          "by_dimension": {
            "fear": "array_of_evidence_objects",
            "hope": "array_of_evidence_objects",
            "enmity": "array_of_evidence_objects",
            "amity": "array_of_evidence_objects",
            "envy": "array_of_evidence_objects",
            "compersion": "array_of_evidence_objects"
          },
          "metadata": {
            "total_quotes": "number",
            "average_confidence": "number"
          }
        }
      }
    },
    "instructions": "IMPORTANT: Your response MUST be a single, valid JSON object containing all required fields with the nested structures specified above. The salience_ranking should be an ordered array of objects, each containing 'dimension', 'salience_score', and 'rank'. All numerical scores must be between 0.0 and 1.0."
  }
}
```

</details> 