# Emotional Climate Framework (ECF) v7.0
**Version**: 7.0
**Status**: Active
**Major Change**: Gasket Architecture with Raw Analysis Log

---

## Overview

ECF analyzes emotional atmosphere in political discourse through six dimensions, independent of rhetorical strategy, speaker character, or institutional effects. Measures psychological environment that discourse generates.

**Purpose**: Objective measurement of emotional climate for audience response prediction and message optimization.

**NEW IN V7.0**: Gasket Architecture with Raw Analysis Log for enhanced data extraction and mathematical processing.

---

## Dimensions

#### Fear (Crisis/Threat Climate) (0.0-1.0)
**Definition**: Language emphasizing danger, threat, vulnerability, crisis, or existential risk.
**Key Markers**: "emergency," "crisis," "under attack," "running out of time," "defenseless"

#### Hope (Opportunity/Progress Climate) (0.0-1.0)  
**Definition**: Language emphasizing positive possibilities, progress, improvement, or achievement potential.
**Key Markers**: "opportunity," "breakthrough," "bright future," "great potential," "optimistic"

#### Enmity (Hostility/Conflict Climate) (0.0-1.0)
**Definition**: Language creating antagonistic atmosphere toward opponents, enemies, or opposing groups.
**Key Markers**: "enemy," "betrayal," "fight against," "destroy," "combat"

#### Amity (Friendship/Unity Climate) (0.0-1.0)
**Definition**: Language fostering positive relationships, cooperation, solidarity, or shared purpose.
**Key Markers**: "together," "unity," "partnership," "cooperation," "shared values"

#### Envy (Resentment/Grievance Climate) (0.0-1.0)
**Definition**: Language expressing resentment toward others' advantages, success, or privileged positions.
**Key Markers**: "unfair advantage," "privileged elite," "deserve better," "left behind," "rigged system"

#### Compersion (Celebration/Merit Climate) (0.0-1.0)
**Definition**: Language celebrating others' success, merit, achievement, or positive developments.
**Key Markers**: "congratulations," "well-deserved," "earned success," "inspiring achievement," "celebration"

---

## Gasket Architecture

### Raw Analysis Log Format
The analysis agent outputs a raw analysis log containing:
- Emotional climate scores for all 6 dimensions
- Salience weights for each dimension
- Evidence quotes with confidence ratings
- Qualitative reasoning about emotional patterns

### Intelligent Extractor Schema
```json
{
  "gasket_schema": {
    "target_keys": [
      "fear_score",
      "hope_score",
      "enmity_score",
      "amity_score",
      "envy_score",
      "compersion_score",
      "fear_salience",
      "hope_salience",
      "enmity_salience",
      "amity_salience",
      "envy_salience",
      "compersion_salience",
      "fear_confidence",
      "hope_confidence",
      "enmity_confidence",
      "amity_confidence",
      "envy_confidence",
      "compersion_confidence"
    ],
    "target_dimensions": [
      "emotional_polarity",
      "climate_intensity"
    ]
  }
}
```

---

<details><summary>Machine-Readable Configuration</summary>

```json
{
  "name": "ecf_v7_0",
  "version": "v7.0",
  "display_name": "Emotional Climate Framework v7.0",
  "analysis_variants": {
    "default": {
      "description": "Complete emotional climate analysis with raw analysis log output.",
      "analysis_prompt": "Phase 1: Cognitive Priming: You are an expert analyst of emotional climate and psychological atmosphere in political discourse. Phase 2: Framework Methodology: Your task is to analyze the emotional climate generated by the provided text using the Emotional Climate Framework v7.0. This framework measures the psychological environment through six key dimensions: Fear, Hope, Enmity, Amity, Envy, and Compersion. Phase 3: Operational Definitions: Evaluate each dimension: Fear (crisis/threat language), Hope (opportunity/progress language), Enmity (hostility/conflict language), Amity (unity/cooperation language), Envy (resentment/grievance language), Compersion (celebration/merit language). Phase 4: Scoring Protocol: For each dimension, provide ONLY: (1) Raw score (0.0-1.0) based on emotional strength, (2) Salience score (0.0-1.0) based on prominence in the message, (3) Confidence score (0.0-1.0) based on evidence strength, (4) Supporting quotes with contextual analysis. DO NOT perform any mathematical calculations or compute derived metrics like polarity or intensity. Phase 5: Raw Analysis Log Requirements: Your response must be a raw analysis log containing dimensional scores, evidence, and reasoning - NO JSON structure or derived calculations. Phase 6: Output Specification: Return raw analysis log with dimensional scores only - NO calculations or derived metrics (these will be computed by code)."
    }
  },
  "dimension_groups": {
    "threat_opportunity": ["fear", "hope"],
    "social_relations": ["enmity", "amity"],
    "resource_attitudes": ["envy", "compersion"]
  },
  "calculation_spec": {
    "emotional_polarity": "(hope + amity + compersion) - (fear + enmity + envy)",
    "climate_intensity": "(fear + hope + enmity + amity + envy + compersion) / 6"
  },
  "reliability_rubric": {
    "cronbachs_alpha": {
      "excellent": [0.80, 1.0],
      "good": [0.70, 0.79],
      "acceptable": [0.60, 0.69],
      "poor": [0.0, 0.59]
    }
  },
  "gasket_schema": {
    "target_keys": [
      "fear_score",
      "hope_score",
      "enmity_score",
      "amity_score",
      "envy_score",
      "compersion_score",
      "fear_salience",
      "hope_salience",
      "enmity_salience",
      "amity_salience",
      "envy_salience",
      "compersion_salience",
      "fear_confidence",
      "hope_confidence",
      "enmity_confidence",
      "amity_confidence",
      "envy_confidence",
      "compersion_confidence"
    ],
    "target_dimensions": [
      "emotional_polarity",
      "climate_intensity"
    ]
  },
  "raw_analysis_log_format": {
    "description": "Raw analysis log containing dimensional scores, evidence, and reasoning without structured JSON",
    "content": "Free-form text with emotional climate analysis including scores, evidence quotes, and qualitative reasoning"
  }
}
```

</details> 